// Generated by scripts/gen-licenses.mjs from the direct dependencies. Do not edit by hand.
export type LicenseEntry = { name: string; version: string; license: string; home: string };

export const LICENSES: readonly LicenseEntry[] = [
  {
    "name": "@maplibre/maplibre-react-native",
    "version": "11.5.0",
    "license": "MIT",
    "home": "https://github.com/maplibre/maplibre-react-native#readme"
  },
  {
    "name": "@trafficnetwork/react-native",
    "version": "1.1.0",
    "license": "Apache-2.0",
    "home": "https://github.com/Romsmo/Trafficnetwork#readme"
  },
  {
    "name": "@types/geojson",
    "version": "7946.0.16",
    "license": "MIT",
    "home": "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/geojson"
  },
  {
    "name": "expo",
    "version": "57.0.26",
    "license": "MIT",
    "home": "https://github.com/expo/expo/tree/main/packages/expo"
  },
  {
    "name": "expo-audio",
    "version": "57.0.5",
    "license": "MIT",
    "home": "https://docs.expo.dev/versions/latest/sdk/audio/"
  },
  {
    "name": "expo-constants",
    "version": "57.0.20",
    "license": "MIT",
    "home": "https://docs.expo.dev/versions/latest/sdk/constants/"
  },
  {
    "name": "expo-dev-client",
    "version": "57.0.19",
    "license": "MIT",
    "home": "https://docs.expo.dev/versions/latest/sdk/dev-client/"
  },
  {
    "name": "expo-file-system",
    "version": "57.0.7",
    "license": "MIT",
    "home": "https://docs.expo.dev/versions/latest/sdk/filesystem/"
  },
  {
    "name": "expo-haptics",
    "version": "57.0.3",
    "license": "MIT",
    "home": "https://docs.expo.dev/versions/latest/sdk/haptics/"
  },
  {
    "name": "expo-keep-awake",
    "version": "57.0.2",
    "license": "MIT",
    "home": "https://docs.expo.dev/versions/latest/sdk/keep-awake/"
  },
  {
    "name": "expo-linking",
    "version": "57.0.11",
    "license": "MIT",
    "home": "https://docs.expo.dev/versions/latest/sdk/linking"
  },
  {
    "name": "expo-localization",
    "version": "57.0.2",
    "license": "MIT",
    "home": "https://docs.expo.dev/versions/latest/sdk/localization/"
  },
  {
    "name": "expo-location",
    "version": "57.0.20",
    "license": "MIT",
    "home": "https://docs.expo.dev/versions/latest/sdk/location/"
  },
  {
    "name": "expo-network",
    "version": "57.0.2",
    "license": "MIT",
    "home": "https://docs.expo.dev/versions/latest/sdk/network/"
  },
  {
    "name": "expo-router",
    "version": "57.0.24",
    "license": "MIT",
    "home": "https://docs.expo.dev/routing/introduction/"
  },
  {
    "name": "expo-secure-store",
    "version": "57.0.4",
    "license": "MIT",
    "home": "https://docs.expo.dev/versions/latest/sdk/securestore/"
  },
  {
    "name": "expo-speech",
    "version": "57.0.3",
    "license": "MIT",
    "home": "https://docs.expo.dev/versions/latest/sdk/speech/"
  },
  {
    "name": "expo-splash-screen",
    "version": "57.0.9",
    "license": "MIT",
    "home": "https://docs.expo.dev/versions/latest/sdk/splash-screen/"
  },
  {
    "name": "expo-status-bar",
    "version": "57.0.1",
    "license": "MIT",
    "home": "https://docs.expo.dev/versions/latest/sdk/status-bar/"
  },
  {
    "name": "expo-system-ui",
    "version": "57.0.4",
    "license": "MIT",
    "home": "https://docs.expo.dev/versions/latest/sdk/system-ui"
  },
  {
    "name": "expo-task-manager",
    "version": "57.0.21",
    "license": "MIT",
    "home": "https://docs.expo.dev/versions/latest/sdk/task-manager/"
  },
  {
    "name": "react",
    "version": "19.2.3",
    "license": "MIT",
    "home": "https://react.dev/"
  },
  {
    "name": "react-dom",
    "version": "19.2.3",
    "license": "MIT",
    "home": "https://react.dev/"
  },
  {
    "name": "react-native",
    "version": "0.86.3",
    "license": "MIT",
    "home": "https://reactnative.dev/"
  },
  {
    "name": "react-native-gesture-handler",
    "version": "2.32.0",
    "license": "MIT",
    "home": "https://docs.swmansion.com/react-native-gesture-handler/"
  },
  {
    "name": "react-native-reanimated",
    "version": "4.5.1",
    "license": "MIT",
    "home": "https://docs.swmansion.com/react-native-reanimated"
  },
  {
    "name": "react-native-safe-area-context",
    "version": "5.7.0",
    "license": "MIT",
    "home": "https://github.com/AppAndFlow/react-native-safe-area-context#readme"
  },
  {
    "name": "react-native-screens",
    "version": "4.26.2",
    "license": "MIT",
    "home": "https://github.com/software-mansion/react-native-screens#readme"
  },
  {
    "name": "react-native-worklets",
    "version": "0.10.1",
    "license": "MIT",
    "home": "https://docs.swmansion.com/react-native-worklets"
  }
];
